Repository aidan-hubley/Prayer-Circle, pull requests merged in 2023-11, with the labels that each got.

#73 circle single tap functionality
  components/Circle.js
Labels: feature

#72 JDA/SettingsV2
  app/(main)/mainViewLayout.js
  app/(main)/profile.js
  app/(settings)/settings.js
Labels: feature

#76 Afm/update user creation
  app/(main)/journal.js
  app/(main)/profile.js
  app/(user)/login.js
  app/(user)/register.js
  app/_layout.js
  app/index.js
  assets/Squared_Logo_Dark.png
  backend/firebaseFunctions.js
  backend/functions.js
  dbstructure.json
Labels: feature, maintenance

#79 Afm/rotary
  app/(create)/createCircle.js
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/mainViewLayout.js
  app/_layout.js
  app/index.js
  babel.config.js
  backend/firebaseFunctions.js
  components/Circle.js
  components/Filter.js
  components/FilterItem.js
  components/Post.js
  dbstructure.json
  package-lock.json
  package.json
Labels: feature

#81 made the icon selector a little less crowded
  components/iconSelector.js
Labels: feature

#83 Created Comments Modal
  components/Post.js
Labels: feature

#78 Changed expo splash page
  app.json
  assets/Dark_Margin.png
Labels: maintenance

#85 update comments modal library
  app/(create)/_layout.js
  app/(create)/createCircle.js
  app/(main)/mainViewLayout.js
  backend/firebaseFunctions.js
  components/Post.js
  package-lock.json
  package.json
Labels: feature

#89 Afm/haptics
  components/Buttons.js
  components/Circle.js
  components/Filter.js
  components/Post.js
  package.json
Labels: feature

#91 better auth state management
  .gitignore
  app/index.js
  backend/firebaseFunctions.js
  package.json
Labels: maintenance

#92 stabilized auth state management
  app/(main)/feed.js
  app/(main)/profile.js
  app/(user)/register.js
  app/index.js
  backend/config.js
  backend/firebaseFunctions.js
  components/Post.js
Labels: maintenance
