Repository aidan-hubley/Prayer-Circle, pull requests merged in 2024-02, with the labels that each got.

#120 Afm/deploy
  .gitignore
  app.json
  app/(auth)/login.js
  app/(auth)/register.js
  app/(aux)/circleSettings.js
  app/(aux)/findCircles.js
  app/(aux)/settings.js
  app/(aux)/shareCircle.js
  app/(create)/_layout.js
  app/(create)/createCircle.js
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/index.js
  app/(main)/journal.js
  app/(main)/profile.js
  app/(settings)/settings.js
  app/(user)/login.js
  app/_layout.js
  app/context/auth.js
  app/filter.js
  app/global.js
  app/index.js
  backend/config.js
  backend/firebaseFunctions.js
  components/BottomSheetModalHelpers.js
  components/Buttons.js
  components/Circle.js
  components/Comment.js
  components/Filter.js
  components/FilterItem.js
  components/Member.js
  components/MemberPermissionSelector.js
  components/Post.js
  components/PostTypeSelector.js
  components/Terms.js
  components/Toggle.js
  components/iconSelector.js
  eas.json
  package.json
Labels: maintenance

#122 Update README.md
  README.md
Labels: documentation

#121 Afm/filter gridview
  backend/firebaseFunctions.js
  components/Filter.js
  components/FilterItem.js
Labels: feature

#123 add functionality to post to different circles
  app.json
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/index.js
  app/(main)/profile.js
  app/global.js
  backend/firebaseFunctions.js
  components/Filter.js
  components/FilterItem.js
  package.json
Labels: feature

#118 Aeh/acc settings functions
  app/(auth)/register.js
  app/(aux)/settings.js
  app/(main)/profile.js
  app/context/auth.js
  backend/firebaseFunctions.js
  components/BottomSheetModalHelpers.js
  components/Post.js
  components/Terms.js
  package.json
Labels: feature

#127 delete post now works with multiselect
  components/Post.js
Labels: bug

#128 Afm/local storage to global vars
  app/(auth)/register.js
  app/(aux)/settings.js
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/index.js
  app/(main)/profile.js
  app/_layout.js
  app/context/auth.js
  app/global.js
  backend/firebaseFunctions.js
  components/Post.js
  components/Toggle.js
  dbstructure.json
Labels: bug, feature

#129 fix sketch post bug and no posts on profile bug
  app/(create)/createPost.js
  app/(main)/profile.js
Labels: bug

#131 add functionality to event date/time selection
  app/(aux)/circleSettings.js
  app/(create)/createPost.js
  backend/functions.js
  components/Post.js
  package.json
Labels: feature

#126 Adaptive icon, icon color, bordercolor, title, and description
  app/(aux)/circleSettings.js
  app/(main)/index.js
  app/global.js
  backend/firebaseFunctions.js
  components/Buttons.js
  components/Comment.js
  components/FilterItem.js
  components/Member.js
  components/Post.js
  package.json
Labels: feature

#133 Bug fixes and touch ups
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/index.js
  app/(main)/profile.js
  backend/firebaseFunctions.js
  components/Circle.js
  components/Comment.js
  components/Filter.js
  components/FilterItem.js
  components/Interaction.js
  components/Member.js
  components/Post.js
  components/PostTypeSelector.js
  components/Toggle.js
Labels: bug, feature

#135 post and filter bug fixes
  app/(aux)/circleSettings.js
  app/(aux)/settings.js
  app/(create)/createCircle.js
  app/global.js
  backend/firebaseFunctions.js
  components/Buttons.js
  components/FilterItem.js
  components/Post.js
Labels: bug

#138 Afm/encryption
  app.config.js
  app.json
  app/(create)/createPost.js
  app/(main)/feed.js
  app/(main)/journal.js
  app/(main)/profile.js
  app/_layout.js
  components/Post.js
  package.json
Labels: feature

#139 Afm/view circles
  app/(main)/index.js
  components/FilterItem.js
  components/Post.js
Labels: feature

#134 add functionality to the member permission selector
  app/(aux)/circleSettings.js
  app/global.js
  backend/firebaseFunctions.js
  backend/functions.js
  components/FilterItem.js
  components/Member.js
  components/MemberPermissionSelector.js
Labels: feature

#140 add functionality to haptics and settings
  app/(aux)/settings.js
  app/_layout.js
  app/global.js
  components/Buttons.js
  components/Circle.js
  components/Filter.js
  components/MemberPermissionSelector.js
  components/Post.js
  components/Toggle.js
Labels: feature

#141 add functionality to report posts
  app/(main)/feed.js
  app/_layout.js
  components/Post.js
Labels: feature

#143 implement new notification type
  app/(auth)/login.js
  app/(auth)/register.js
  app/(aux)/findCircles.js
  app/(aux)/settings.js
  app/(create)/createCircle.js
  app/(create)/createPost.js
  app/_layout.js
  app/context/auth.js
  app/global.js
  components/MemberPermissionSelector.js
  components/Post.js
  package.json
Labels: feature, maintenance

#137 Aeh/unfiltered settings page
  .gitignore
  .vscode/settings.json
  app/(auth)/register.js
  app/(aux)/prayerCircleInfo.js
  app/(aux)/settings.js
  app/(create)/createPost.js
  app/(main)/index.js
  app/_layout.js
  assets/adaptive-icon.png
  assets/devs/aidan.jpg
  assets/devs/alex.jpg
  assets/devs/andrew.jpg
  assets/devs/justin.jpg
  assets/devs/nason.jpg
  assets/logos/googleForm.png
  backend/firebaseFunctions.js
  components/Filter.js
  components/FilterItem.js
  components/Terms.js
Labels: feature

#142 Afm/bugs
  app/(aux)/circleSettings.js
  components/Comment.js
  components/MemberPermissionSelector.js
  components/Post.js
Labels: bug

#147 Nra/leave and delete circle
  app/(aux)/circleSettings.js
  app/(main)/index.js
Labels: feature

#149 implemented native datetime picker, and functions to respect timezone
  app/(create)/createPost.js
  backend/functions.js
  components/Post.js
  package.json
Labels: feature, maintenance

#150 fix post title cropping
  components/Post.js
Labels: bug
